### ISSUE TITLE
Can't Save or Modify Abbreviations in Debian 13

### ISSUE THREAD

**Issue by Lonniebiz** [autokey/autokey#1048]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [x] I have searched through the existing issues.

### Is this a question rather than an issue?

- [x] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [x] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [x] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Debian: 13
"Desktop": Awesome Window Manager (xorg)

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

autokey-gtk: 0.96.0 (installed via apt)

### How did you install AutoKey?

sudo apt install autokey-gtk

### Can you briefly describe the issue?

I cannot modify or save abbreviations.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1) Launch Autokey without any pre-existing .config
2) My Phrases > Addresses > Home Address
3) Click the "Set" button for Abbreviations
4) remove "adr"
5) Add ";adr" (I always prepend a ';' for all abbreviations to prevent accidental triggering in the wild)
6) Press enter (a silly necessary step going back a long time)
7) Click the "OK" button

### What should have happened?

It should save the modified abbreviation, and the dialog should go away as confirmation.

### What actually happened?

The dialog remains (ignoring "OK" button-clicks) until you click the "Cancel" button.

### Do you have screenshots?

<img width="100%" alt="Image" src="https://github.com/user-attachments/assets/b13dd534-f73a-4dcc-bd98-5be09beed60a" />

### Can you provide the output of the AutoKey command?

```bash
2025-08-24 18:21:35,575 DEBUG - autokey.service - Window visible title: 'Set Abbreviations', Window class: 'autokey-gtk.Autokey-gtk'
2025-08-24 18:21:37,301 DEBUG - autokey.service - Raw key: <Key.ENTER: '<enter>'>, modifiers: [], Key: Key.ENTER
2025-08-24 18:21:37,301 DEBUG - autokey.service - Window visible title: 'Set Abbreviations', Window class: 'autokey-gtk.Autokey-gtk'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/autokey/gtkui/dialogs.py", line 86, in on_ok
    if self.valid():
       ~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/autokey/gtkui/dialogs.py", line 353, in valid
    len(self.get_abbrs()) > 0,
        ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/autokey/gtkui/dialogs.py", line 336, in get_abbrs
    text = model.get_value(i.next().iter, 0)
                           ^^^^^^
AttributeError: 'TreeModelRowIter' object has no attribute 'next'
```

### Anything else?

I'm astonished that Debian 13 Stable made Autokey-GTK 0.96.0 default. The last stable version I've used is Autokey-GTK 0.95.10-2, which was default in Debian 12 Stable. I may have to downgrade back to Debian 12; running 0.95.10-2 on Debian 13 comes with its own baggage.

Autokey-GTK, is my number one most important productivity application. Autokey-GTK 0.96.0 can't use my existing config from 0.95.10-2, and even with a new default config it doesn't work either.

Again, I can't believe this version of Autokey-GTK made it into Debian 13 Stable; you'd think someone would have caught this in the testing branch.
Please direct me to any documentation that might get my "decade and half" worth of phrases, scripts, hotkeys, and abbreviations working in Autokey-GTK 0.96.0.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #1048</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Lonniebiz</code> (replace <code>20</code> with the amount, and <code>@Lonniebiz</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by Elliria** [comment]
That's a [known issue](https://github.com/autokey/autokey/issues/646#issuecomment-2996981726) caused by the next method being deprecated in Python. Our code-base is currently in a holding pattern as part of a transition, so we're not able to edit the code.

The temporary work-around for it is:
1. Edit the `/usr/lib/python3/dist-packages/autokey/gtkui/dialogs.py` file.
2. Replace this Python 2 syntax:
    ```python
    text = model.get_value(i.next().iter, 0)
    ```
    with this Python 3 syntax:
    ```python
    text = model.get_value(next(i).iter, 0)
    ```

**Comment by Lonniebiz** [comment]
That worked for saving abbreviations. Thank you for the prompt reply.

**Comment by Elliria** [comment]
Oh, good to hear! Thank you for letting me know. I'm glad it worked.

It's one of many tasks that will be taken care of in the next release once we're back to being able to edit the code.

**Comment by damufo** [comment]
Debian 13
XFCE
Solution
https://github.com/autokey/autokey/issues/1048#issuecomment-3218472219
not work for me

**Comment by Elliria** [comment]
I'm sorry, @damufo. Hopefully, we'll be able to figure it out.

Which version of AutoKey are you using?

Also, after making the recommended change in [that comment](https://github.com/autokey/autokey/issues/1048#issuecomment-3218472219), did you follow every one of the steps listed above for reproducing the issue? If step 6 is left out, it will cause the problem.

If you did follow all of the steps and still can't save or modify an abbreviation, can you create a traceback (log) by following [these instructions in the AutoKey wiki](https://github.com/autokey/autokey/wiki/Troubleshooting#autokey-traceback) and paste its output into a message here so we can see what's going on?

**Comment by damufo** [comment]
Thanks @Elliria.
Debian 13 installed autokey-gtk by apt
Version 0.96.0
I reboot and work fine!!
Solution
https://github.com/autokey/autokey/issues/1048#issuecomment-3218472219
Work for me! 🙂
Very thanks!

**Comment by Elliria** [comment]
Oh, that's terrific news. As Hannibal in the "A-Team" television series liked to say, "I love it when a plan comes together."

**Comment by Elliria** [comment]
Related issues:
* [issue #646](https://github.com/autokey/autokey/issues/646)
* [issue #1059](https://github.com/autokey/autokey/issues/1059)
* [issue #974](https://github.com/autokey/autokey/issues/974)
* [issue #1013](https://github.com/autokey/autokey/issues/1013)

**Comment by gitressa** [comment]
Thanks @Elliria! [The method you shared Aug 25, 2025](https://github.com/autokey/autokey/issues/1048#issuecomment-3218472219) worked like a charm, and abbreviations can be saved.

**Comment by cristianbupo** [comment]
Xubuntu 25.10
autokey 0.96.0
i3 4.24

Editing the `/usr/lib/python3/dist-packages/autokey/gtkui/dialogs.py` file and rebooting works!

**Comment by josephj11** [comment]
@cristianbupo Thanks. What changes did you make? A diff would be great.

**Comment by Elliria** [comment]
I think that was in reference to [this message above](https://github.com/autokey/autokey/issues/1048#issuecomment-3218472219). I took a look and the fix for this is already part of pull request #1076, so it will definitely be in our next release.

**Comment by cristianbupo** [comment]
Yes it was, thanks for the support!

**Comment by Elliria** [comment]
Closing this issue manually since the issue has been resolved in pull request #1076.
