### ISSUE TITLE
Unable to save changes when abbreviation is defined

### ISSUE THREAD

**Issue by muekoeff** [autokey/autokey#974]
### AutoKey is a Xorg application and will not function in a Wayland session. Do you use Xorg (X11) or Wayland?

Xorg

### Has this issue already been reported?

- [X] I have searched through the existing issues.

### Is this a question rather than an issue?

- [X] This is not a question.

### What type of issue is this?

Bug

### Choose one or more terms that describe this issue:

- [ ] autokey triggers
- [X] autokey-gtk
- [ ] autokey-qt
- [ ] beta
- [X] bug
- [ ] critical
- [ ] development
- [ ] documentation
- [ ] enhancement
- [ ] installation/configuration
- [ ] phrase expansion
- [ ] scripting
- [ ] technical debt
- [ ] user interface

### Which Linux distribution did you use?

Distributor ID:	Arch
Description: Arch Linux

### Which AutoKey GUI did you use?

GTK

### Which AutoKey version did you use?

0.96.0

### How did you install AutoKey?

[AUR](https://aur.archlinux.org/pkgbase/autokey)

### Can you briefly describe the issue?

Using the GTK-GUI, when trying to edit a phrase that as at least one abbreviation set I'm unable to save.

Additionally, when having the Abbreviations dialog open and at least one abbreviation set, clicking on “OK” does nothing.

### Can the issue be reproduced?

Always

### What are the steps to reproduce the issue?

1. Open AutoKey GTK-GUI.
2. Select one already set phrase that already has an abbreviation.
3. Edit it.
4. Click on “Save”.

### What should have happened?

Changes should have been saved.

### What actually happened?

The GUI remains responsive but I'm now unable to navigate to other phrases or exit it by clicking “Quit” in the tray's context menu.

### Can you provide the output of the AutoKey command?

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/autokey/gtkui/configwindow.py", line 979, in on_save
    if self.__getCurrentPage().validate():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/autokey/gtkui/configwindow.py", line 717, in validate
    errors += self.settingsWidget.validate()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/autokey/gtkui/configwindow.py", line 201, in validate
    abbreviations, modifiers, key, filterExpression = self.get_item_details()
                                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/autokey/gtkui/configwindow.py", line 221, in get_item_details
    abbreviations = self.abbrDialog.get_abbrs()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/autokey/gtkui/dialogs.py", line 336, in get_abbrs
    text = model.get_value(i.next().iter, 0)
                           ^^^^^^
AttributeError: 'TreeModelRowIter' object has no attribute 'next'
```

<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #974</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @muekoeff</code> (replace <code>20</code> with the amount, and <code>@muekoeff</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

**Comment by josephj11** [comment]
OK. This is two separate issues.

One is a longstanding _undocumented_ deficiency in the GUI. Once you add an abbreviation, you have to press Enter to make it stick. Your write-up suggests you didn't know that. That's on us.

Try adding that step and see what happens.

I was expecting that would be the whole thing, but then there's the traceback.

Currently, AutoKey is (officially) supported to work on Python 3.9 - 3.11. We have a fix for one known 3.12 issue #973, which is being added for our next release. It looks initially like this might be another one.

@Elliria - any idea how this relates to Python 3.12, if at all? 

If you're good enough  with Python (I'm not), can you run this in a Python 3.11 venv, etc. and see if the exception goes away?

Note that while we have several members helping out with small development tasks, we don't have a project developer. Until someone wants to do that, we can't make a new release at all.

**Comment by Elliria** [comment]
It looks like the `next()` method was deprecated in Python 3 (not sure which version) in favor of `__next__`. There's one occurrence of it in the [dialogs.py](https://github.com/autokey/autokey/blob/e38f020aa49d3e9530041872551cd0a3b508ab34/lib/autokey/gtkui/dialogs.py#L336) file

**Comment by josephj11** [comment]
@Elliria Good. That sounds easy to fix. This whole fork started in Python3, so the problem must be newer than that because we haven't seen it before.

Looks like this may be a 3.12 thing.

Venice says:

The next() function was deprecated in Python 3.12 and will be removed in version 3.14. This means that using next() in your Python program will result in a warning, and eventually, it will stop working altogether. You can refer to the Python documentation for more information on this change and how to update your code accordingly. It's recommended to start updating your code to use alternative methods, such as the next(iter(...)) or next(iterator) syntax, to avoid any issues when you upgrade to Python 3.14 or later.

what else was depreciated like that in 3.12?

Apart from the next() function, several other features and functionalities were deprecated in Python 3.12. Some notable examples include:

The lru_cache function no longer supports pickling.
The functools.total_ordering decorator no longer supports subclassing.
The collections.OrderedDict class now behaves like a regular dictionary.
The unittest.mock.patch.object method now requires a spec parameter.
To find out more about these changes and how to update your code, you can refer to the Python documentation and the release notes for Python 3.12.

**Comment by Elliria** [comment]
This [Stack Exchange page](https://stackoverflow.com/questions/18547878/attribute-error-next) demonstrates this offending line of code:
```
for root, dirs, files in os.walk(dir).next(1): 
```
One of the solutions is this replacement line of code:
```
for root, dirs, files in os.walk(dir).__next__()[1]:
```
[This](https://github.com/autokey/autokey/blob/e38f020aa49d3e9530041872551cd0a3b508ab34/lib/autokey/gtkui/dialogs.py#L336) is our offending line of code:
```
text = model.get_value(i.next().iter, 0)
```
It's possible that replacing it with this line (following the last example on that Stack Exchange page) would solve the issue:
```
text = model.get_value(i.__next__().iter, 0)
```
I haven't tested it because I use Python 3.10, which doesn't have the issue. Tests are welcome.

**Comment by Elliria** [comment]
Thanks for the heads-up on Python 3.12.

I did a search for each of those possible issues in AutoKey's code and it looks like two files will be affected:
* [lru_cache](https://github.com/search?q=repo%3Aautokey%2Fautokey+lru_cache&type=code) will need to be dealt with.
* We don't use functools.total_ordering.
* We don't use ordered dicts.
* [unittest.mock.patch.object](https://github.com/search?q=repo%3Aautokey%2Fautokey+unittest.mock.patch&type=code) will need to be dealt with.

**Comment by muekoeff** [comment]
> Your write-up suggests you didn't know that.

I actually meant that clicking “OK” does literally nothing at all. Not even closing the dialog window. Clicking on it causes the same exception as reported above. Whether I hit Enter after having edited the label's text does not make a difference.

> […] can you run this in a Python 3.11 venv, etc. and see if the exception goes away?

I tried my hand at using pyenv and got the same exception:

```
Traceback (most recent call last):
  File "~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/autokey/gtkui/dialogs.py", line 86, in on_ok
    if self.valid():
       ^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/autokey/gtkui/dialogs.py", line 353, in valid
    len(self.get_abbrs()) > 0,
        ^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.0/lib/python3.11/site-packages/autokey/gtkui/dialogs.py", line 336, in get_abbrs
    text = model.get_value(i.next().iter, 0)
                           ^^^^^^
AttributeError: 'TreeModelRowIter' object has no attribute 'next'
```



<details>
<summary>

`./pip list` output:

</summary>

```
ansible-pylibssh   1.1.0
autokey            0.96.0
dbus-python        1.3.2
importlib-metadata 6.6.0
jaraco.classes     3.2.3
keyring            23.13.1
packaging          24.2
pip                22.3
pycairo            1.27.0
PyGObject          3.50.0
pyinotify          0.9.6
python-xlib        0.33
SecretStorage      3.3.3
setuptools         65.5.0
six                1.16.0
zipp               3.15.0
```

</details>

**Comment by josephj11** [comment]
@Elliria Venice said those were the most common differences, not all of them. I'm not sure how to tease a full list out of the release notes. This does clearly illustrate why we need those tox tests!

**Comment by muekoeff** [comment]
Replacing `text = model.get_value(i.next().iter, 0)` with `text = model.get_value(i.__next__().iter, 0)` indeed resolved the issue.

**Comment by Elliria** [comment]
That's great news, @muekoeff! I'll make the change officially once we're sure whether we can make changes while the Wayland code is being worked on or not and if not, it will go onto the back burner until the change can be made. It's the only instance of it in the code, so it won't need to be changed in any of the other files.

**Comment by Elliria** [comment]
@josephj11, the [Python Documentation by Version](https://www.python.org/doc/versions/) offers all of them and the first link on each page tells you what's new in it.

Interestingly, the `next()` method got renamed to `__next__()` in Python 3.0 as part of [PEP 3114](https://peps.python.org/pep-3114/).

Even more interestingly, although the `next()` method is in the same file in AutoKey 0.95.10, which is what I'm using, I can't replicate the issue. I can freely change the abbreviation over and over and AutoKey behaves normally.

**Comment by josephj11** [comment]
@Elliria Thanks. I suspect you can't replicate it on the old AutoKey is because it also uses an old Python where the change hasn't happened yet.

Doesn't the new name for next make it an "internal" function? I got the impression that you normally weren't supposed to use those (not guaranteed to be there later...) and that maybe the other suggestions from Venice might be better fixes although they still seem to use a variant of the function, so I don't see how they are any better.

I just read the linked PEP, but didn't understand it enough to get any clarity on the issue.

**Comment by muekoeff** [comment]
As far as I understand the PEP, the idiomatic replacement that avoids calling internal functions would be:
(which also works, by the way)

```python
text = model.get_value(next(i).iter, 0)
```

**Comment by Elliria** [comment]
Interestingly, the [PEP](https://peps.python.org/pep-3114/) mentions it as exception to the usual naming convention:

> The use of double underscores creates a separate namespace for names that are part of the Python language definition, so that programmers are free to create variables, attributes, and methods that start with letters, without fear of silently colliding with names that have a language-defined purpose. (Colliding with reserved keywords is still a concern, but at least this will immediately yield a syntax error.)

> The naming of the next method on iterators is an exception to this convention. Code that nowhere contains an explicit call to a next method can nonetheless be silently affected by the presence of such a method. Therefore, this PEP proposes that iterators should have a __next__ method instead of a next method (with no change in semantics).

However, @muekoeff's use of the `next()` function instead of the `__next__()` method is the perfect alternative and we'll use that as soon as we sort out the PRs on the **develop** branch.

**Comment by GitHub-Lover** [comment]
> Replacing `text = model.get_value(i.next().iter, 0)` with `text = model.get_value(i.__next__().iter, 0)` indeed resolved the issue.

Thank you so much 👏

**Comment by trapier** [comment]
Added the following to my `configuration.nix` on nixos:

```
  nixpkgs.overlays = [(
      final: prev: {
        autokey = prev.autokey.overrideAttrs (upstream: {
          patches = (upstream.patches or []) ++ [
            # https://github.com/autokey/autokey/issues/974#issuecomment-2487007454
            (builtins.toFile "python3next.patch" ''
              diff --git a/lib/autokey/gtkui/dialogs.py b/lib/autokey/gtkui/dialogs.py
              index 6f0dada..79b69f6 100644
              --- a/lib/autokey/gtkui/dialogs.py
              +++ b/lib/autokey/gtkui/dialogs.py
              @@ -333,7 +333,7 @@ class AbbrSettingsDialog(DialogBase):
                       # TODO: list comprehension or for loop, instead of manual loop
                       try:
                           while True:
              -                text = model.get_value(i.next().iter, 0)
              +                text = model.get_value(i.__next__().iter, 0)
                               ret.append(text)
                               # ret.append(text.decode("utf-8"))
                       except StopIteration:
            '')
          ];
        });
      }
    )
  ];
```

I look forward to `nixos-rebuild` failing to apply that patch once nixpkgs picks up a version with the fix for this issue.

**Comment by Elliria** [comment]
Does @muekoeff's use of the **next()** function instead of the **__next__()** method  work for you?
```python
text = model.get_value(next(i).iter, 0)
```

**Comment by josephj11** [comment]
@Elliria I don't understand the mechanism @trapier is using, but looking at it, I can see that it applies the same fix you are referring to.

**Comment by Elliria** [comment]
The difference is subtle:

* @trapier's solution removes the **next()** method and replaces it with the private **__next__()** method:
  1. Remove this:
     ```
     text = model.get_value(i.next().iter, 0)
     ```
  2. Replace it with this:
     ```
     text = model.get_value(i.__next__().iter, 0)
     ```

* @muekoeff's solution removes the **next()** method and replaces it with the **next()** function:
  1. Remove this:
     ```
     text = model.get_value(i.next().iter, 0)
     ```
  2. Replace it with this:
     ```
     text = model.get_value(next(i).iter, 0)
     ```

If you put the two solutions on top of one another, the difference is more noticeable:
```
text = model.get_value(i.__next__().iter, 0)
text = model.get_value(next(i).iter, 0)
```
Either will work, but @muekoeff's solution uses the recommended Pythonic replacement for the deprecated **next()** method.

**Comment by Elliria** [comment]
I've added this to my personal ToDo list of things to do once we can edit the code again, so this fix will be part of the next release.

**Comment by Elliria** [comment]
Related issues:
* [issue #646](https://github.com/autokey/autokey/issues/646)
* [issue #1048](https://github.com/autokey/autokey/issues/1048)
* [issue #1059](https://github.com/autokey/autokey/issues/1059)
* [issue #1013](https://github.com/autokey/autokey/issues/1013)

**Comment by Elliria** [comment]
Closing this issue manually since the issue has been resolved in pull request #1076.
